apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: multgame/web-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
