apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-prod
resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
  - hpa.yaml
  - default-serviceaccount.yaml
secretGenerator:
  - name: app-secrets
    literals:
      - JWT_SECRET=replace-me
      - REPORT_SHARED_SECRET=replace-me
  - name: redis-secrets
    literals:
      - REDIS_PASSWORD=replace-me
patches:
  - path: patches/game-server.yaml
  - path: patches/api-server.yaml
  - path: patches/ws-router.yaml
  - path: patches/redis.yaml
  - path: patches/ingress.yaml
  - path: patches/api-config.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: multgame/game-server
    newName: ghcr.io/fibbonaccibear/multgame-game-server
    newTag: latest
  - name: multgame/api-server
    newName: ghcr.io/fibbonaccibear/multgame-api-server
    newTag: latest
  - name: multgame/ws-router
    newName: ghcr.io/fibbonaccibear/multgame-ws-router
    newTag: latest
  - name: multgame/web-client
    newName: ghcr.io/fibbonaccibear/multgame-web-client
    newTag: latest
