apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  PORT: "8081"
  REDIS_ADDR: "redis:6379"
  TOKEN_TTL: "10m"
  REGISTRY_CLEANUP_INTERVAL: "15s"
  PUBLIC_GAME_WS_URL: "ws://localhost:8080/ws"
  WS_ROUTER_BASE_URL: "ws://multgame.localtest.me/ws"
  SPECTATOR_MODE_ENABLED: "false"
