apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-router
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ws-router
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 256Mi
