apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
configMapGenerator:
  - name: grafana-dashboards
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
    files:
      - dashboards/multgame-overview.json
