apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-dev
resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
secretGenerator:
  - name: app-secrets
    literals:
      - JWT_SECRET=dev-secret
      - REPORT_SHARED_SECRET=dev-report-secret
  - name: redis-secrets
    literals:
      - REDIS_PASSWORD=
patches:
  - path: patches/game-server.yaml
  - path: patches/api-server.yaml
  - path: patches/ws-router.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: multgame/game-server
    newTag: latest
  - name: multgame/api-server
    newTag: latest
  - name: multgame/ws-router
    newTag: latest
  - name: multgame/web-client
    newTag: latest
